#!/bin/bash
# ----------------------------------------------------------------------
# This script is intended for macOS and runs the project tests using
# all browsers supported on Mac.  This script is for testing during
# development on this project.
# ----------------------------------------------------------------------

prompt-to-proceed () {
  read -p "Do you wish to proceed (Press any key to continue or 'n' to exit)? " response
  if [[ $response == 'n' ]] || [[ $response == 'N' ]]; then
    echo " buh-bye"
    echo ""
    exit
  fi
  echo ""
}

run_command () {
  echo "  Executing [$@]..."
  # quote to preserve spaces and args
  "$@"
  echo "  ... [$@] completed"
  echo ""
}

load_if_dotenv_file () {
  if [[ -f .env ]]; then
    echo "Found .env file, loading it"
    export $(cat .env | xargs)
    echo ""
  fi
}

### MAIN ###
# Exit script on any errors
set -e

echo "Testing the NATIVE sample project - macOS only"
echo ""

load_if_dotenv_file

echo "Running dotnet restore"
prompt-to-proceed
run_command dotnet restore
echo ""

run_tests_command="${RUN_TESTS_COMMAND-./SampleCSharpXunitSelenium/script/run tests}"

echo "Testing default"
run_command dotnet test

echo "Testing Chrome..."
echo "Chrome Headed"
BROWSER_TYPE=chrome run_command $run_tests_command

echo "Chrome Headless"
HEADLESS=true BROWSER_TYPE=chrome run_command $run_tests_command

echo "Testing Edge..."
echo "Edge Headed"
BROWSER_TYPE=edge run_command $run_tests_command

echo "Edge Headless"
HEADLESS=true BROWSER_TYPE=edge run_command $run_tests_command

echo "Testing Firefox..."
echo "Firefox Headed"
BROWSER_TYPE=firefox run_command $run_tests_command

echo "Firefox Headless"
HEADLESS=true BROWSER_TYPE=firefox run_command $run_tests_command

echo "Testing Safari (Headed Sequential)"
BROWSER_TYPE=safari run_command $run_tests_command

echo "--- ALL TESTS PASSED ---"
echo ""
echo "--- FIN ---"
