#!/bin/sh

# Exit script on any errors
set -e

# Run dotnet format --verify-no-changes which has no zero return code
# Pass through any arguments
run_command="dotnet format --verify-no-changes $@"

# Generic run command and catch error
echo "RUNNING [${run_command} ]..."
# Allow to fail but catch return code
set +e
$run_command
run_return_code=$?
# NOTE return code must be caught before any other command
set -e
echo ''

echo "EXITING WITH RUN RETURN CODE [${run_return_code}]"
exit $run_return_code
